### ISSUE TITLE
Build timeline

### ISSUE THREAD

**Issue by kristensantee** [kitanablade/curarte#6]
- [x] establish due dates/times
- [x] create follow-up/reminders

7/7 **FIRST MODEL** -
- [x] Wireframe/discussion of concept
- [x] Add branches
- [x] Test to retrieve artwork data and create basic structure of website
- [x] Console checks
- [x] Basic HTML, CSS and Javascript to prove functionality
- [x] API functionality
- [x] 1:15p - First day pitch
- [x] Begin formatting the website based on the wireframe 

7/8 **BIG WORK DAY** -
- [x] Continue formatting the website based on the wireframe 
- [x] Implement the 2 server-side API
- [x] Implement search filter
- [x] Implement "Wishlist"
- [x] Add the cards for the artwork
- [x] Begin working on buttons and Wikipedia API
- [x] Navbar (if not already implemented)

7/9 **WEEKEND WORK** -
- [x] Continue implementing whatever wasn't fully complete on Friday
- [x] Front and Back end Cleanup (WHERE NEEDED)

7/10 **WEEKEND WORK**  -
- [x] Continue implementing whatever wasn't fully complete on Friday
- [x] Front and Back end Cleanup (WHERE NEEDED)

7/11 **REGROUP FIXES** -
- [x] All back-end should be ready by the end of the class session
- [x] Make sure links are functional
- [x] Touchup CSS and visuals to look like wireframe

7/12 **FIXES** -
- [x] Touchup CSS and visuals
- [x] Touchup Script making sure there are no major bugs
- [x] Practice presentation

7/13 **TURN IN DATE** -
- [x] Presentation Day!
- [x] Final fixes (check for readability, reusability, modifiability, and ease of use)
- [x] Deploy to GitHub Pages if haven't already been done
- [x] Fill out README, be sure to add images

**Comment by nickjestes** [comment]
7/7 **FIRST MODEL** -
- [ ] Wireframe/discussion of concept
- [ ] Add branches
- [ ] Test to retrieve artwork data and create basic structure of website
- [ ] Console checks
- [ ] Basic HTML, CSS and Javascript to prove functionality
- [ ] API functionality
- [ ] 1:15p - First day pitch
- [ ] Begin formatting the website based on the wireframe 
7/8 **BIG WORK DAY** -
- [ ] Continue formatting the website based on the wireframe 
- [ ] Implement the 2 server-side API
- [ ] Implement search filter
- [ ] Implement "Wishlist"
- [ ] Add the cards for the artwork
- [ ] Begin working on buttons and Wikipedia API
7/9 **WEEKEND WORK** -
- [ ] Continue implementing whatever wasn't fully complete on Friday
- [ ] Back-end Cleanup (IF NEEDED)
- [ ] Navbar (if not already implemented)
7/10 **WEEKEND WORK**  -
- [ ] Continue implementing whatever wasn't fully complete on Friday
- [ ] Back-end cleanup (IF NEEDED)
- [ ] Finish Wikipedia buttons
7/11 **REGROUP FIXES** -
- [ ] All back-end should be ready by the end of the class session
- [ ] Make sure links are functional and 
- [ ] Touchup CSS and visuals
7/12 **FIXES** -
- [ ] Touchup CSS and visuals
- [ ] Touchup Script making sure there are no major bugs
- [ ] Work on Presentation
7/13 **TURN IN DATE** -
- [ ] Presentation Day!
- [ ] Final fixes (check for readability, reusability, modifiability, and ease of use)
- [ ] Deploy to GitHub Pages if haven't already been done
- [ ] Fill out README, be sure to add images
